import axios from 'axios';
import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useState } from 'react'


// const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  // const [data,setData] = useState([]);

  // async function dataFun(){
  //   const res = await axios.get(`/api`)
  //   setData(res.data)
  // }

  // useEffect(()=>{dataFun()},[])

  // if(!data) return(<></>)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          data.map((obj) => {
            return <p key={obj.name}>
                      <Link href={`/detail/${obj.name}`}>
                        <img src={obj.url} alt={obj.name}/>
                      </Link>
                  </p>
          })
        }
      </main>
     
    </>
  )
}



export async function getServerSideProps(){
  const res = await axios.get(`http://localhost:3000/api`)
  const data = res.data

  return {props: {data}}
}